### ISSUE TITLE
uBlock Origin Extra vs wowhead.com

### ISSUE THREAD

**Issue by Kekondra** [gorhill/uBO-Extra#37] opened 2017-03-27 22:37 UTC
With uBlock Origin Extra:
![image](https://cloud.githubusercontent.com/assets/26726463/24380993/219b4eb2-135f-11e7-97d4-ce75a23b8690.png)

Without uBlock Origin Extra:
![image](https://cloud.githubusercontent.com/assets/26726463/24381008/3100e75e-135f-11e7-9889-da7a846b4541.png)

uBO-Extra version 2.17
uBlock Origin version 1.11.4
Google Chrome 57.0.2987.110

I got these spaces even with default RU AdList filters and nothing more. No ads, just this empty spaces, why this is happening?

**Comment by Kekondra** [comment] 2017-03-27 22:44
I think this is because of this:
https://github.com/gorhill/uBO-Extra/commit/00a46ee65cf86d153b0a99817123accdc26e25e5

> +            'zam.com',

I use uBO-Extra long time and got this issue only recently. Zam is wowhead owner.

**Comment by Mmocham** [comment] 2017-03-27 23:05
And also http://www.mmo-champion.com/content/ (as wowhead.com) loading strange now. When i click open this site it's loading, then stop, then loading again and open site. Without ubo extra site is opens Instantly, what do you change in ubo extra? I never have issues like this before.

**Comment by okiehsch** [comment] 2017-03-27 23:17
Here is a screenshot without uBO-Extra and uBO with default settings

![woww](https://cloud.githubusercontent.com/assets/16838044/24382023/04f374fc-1354-11e7-82fb-707c41d3cdc3.JPG)

If I add `wowhead.com##script:inject(abort-on-property-write.js, MonkeyBroker)`
I can reproduce your second screenshot with uBO-Extra enabled.
![wowh](https://cloud.githubusercontent.com/assets/16838044/24381682/dbd3b142-1351-11e7-8af5-4d907226a9ed.JPG)
so the reason appears to be MonkeyBroker.

**Comment by Mmocham1** [comment] 2017-03-27 23:25
What is MonkeyBroker? I don't have any filter with this rule.

**Comment by Mmocham1** [comment] 2017-03-27 23:29
Why without ubo extra i dont need to add any rules to hide empty space from ads, but with ubo extra i need to add this rule? Why it can't be fixed in ubo extra?

**Comment by 10101010011** [comment] 2017-03-28 01:02
Also i read feedback in chrome store and see this:

> since 2017feb22, chrome bug 129353 (the cause for this extension) is fixed. Do we still need the extension? As of 2017mar04, it's in Chrome 58.

https://bugs.chromium.org/p/chromium/issues/detail?id=129353

It's really fixed, so ubo-extra is useless now?

**Comment by gorhill** [comment] 2017-03-28 01:40
@okiehsch I get the same as you.

@Kekondra  Are you using something else, other extension(s)? This needs to be disclosed.

**Comment by gorhill** [comment] 2017-03-28 01:44
How about: `wowhead.com##.blocks`?

**Comment by bulihunew** [comment] 2017-03-28 01:58
@gorhill no extensions except ublock origin & ublock origin extra. I have these rules also:

>||stanza.co/*
>wowhead.com##.stanzacal

Because w/o this rules wowhead is very laggy.


> wowhead.com##.blocks

This rule does nothing with right-side empty space, only hiding top.


Also http://www.mmo-champion.com is fine w/o uBO-Extra, but with him it's loading not instantly


> uBO-Extra removes all that crap and the site is snappy again. 

uBO-Extra just cancels requests when i press F5:
![image](https://cloud.githubusercontent.com/assets/26729004/24385517/8a1ac01e-137b-11e7-8752-703b10192e1f.png)
And then anyway load them again:
![image](https://cloud.githubusercontent.com/assets/26729004/24385519/8cd1154c-137b-11e7-8580-6fcd3eb95b70.png)

**Comment by gorhill** [comment] 2017-03-28 04:36
> And all is fine without uBO-Extra

All is not fine without uBO-Extra. You can't see it with the dev console because the site will behave differently when the dev console is opened. Use uBO's logger and see for yourself:

![a](https://cloud.githubusercontent.com/assets/585534/24389301/6cb76aea-134e-11e7-92ef-f05ad6987901.png)

See <https://github.com/uBlockOrigin/uAssets/issues/227>.

**Comment by ximanuyewe** [comment] 2017-03-28 12:44
@gorhill i have same result with ubo extra and without, maybe you don't use some filters?
![image](https://cloud.githubusercontent.com/assets/26741202/24405381/c0d5bf6e-13d5-11e7-818c-3787fa405e38.png)


I dont even have requests with "g00" in adresses.

**Comment by gorhill** [comment] 2017-03-28 13:09
I get the g00 stuff with all your filter lists. As said, Instart Logic code detects whether the console is opened,  detect the user agent (they don't serve their nasty code on Firefox), and what else has not been spotted now, maybe some sort of geolocation.

If you do not need uBO-Extra, don't use it, but uBO-Extra is definitely useful for those getting the Instart Logic crap, and to see if you get it, close the dev console, and open the uBO's logger.

**Comment by ximanuyewe** [comment] 2017-03-28 13:14
@gorhill i use ubo console, there is no g00 in it anyway.

**Comment by ximanuyewe** [comment] 2017-03-28 13:20
Can you fix wowhead empty spaces without adding rules to uBO like

> wowhead.com##script:inject(abort-on-property-write.js, MonkeyBroker)

?

**Comment by gorhill** [comment] 2017-03-28 13:47
I can fix what I can reproduce. I posted a cosmetic filter for what I could reproduce: `wowhead.com##.blocks`.

**Closed** 2017-03-28 16:29 UTC

**Comment by ximanuyewe** [comment] 2017-03-28 17:00
@gorhill  this does not fix right sidebar empty space...
![image](https://cloud.githubusercontent.com/assets/26741202/24417434/77b77876-13f9-11e7-95a1-a4db1a5f8fe5.png)


This - `wowhead.com##script:inject(abort-on-property-write.js, MonkeyBroker)` is fix it.
![image](https://cloud.githubusercontent.com/assets/26741202/24417462/946c93b6-13f9-11e7-8897-c95ef7fc3de3.png)

**Comment by gorhill** [comment] 2017-03-28 17:30
> why there is no these empty spaces without uBO-Extra?

uBO-Extra removes inline javascript tag from the page, which javascript is responsible for the nasty g00 stuff. I suppose that nasty javascript is responsible for removing those placeholders?

**Comment by gorhill** [comment] 2017-03-28 17:36
This is what uBO-Extra fixes on wowhead: <https://us.battle.net/forums/en/wow/topic/20753230780?page=99#post-1975>.

**Comment by uBlock-user** [comment] 2017-03-28 18:07
That IL crap behaves differently with each version of Chromium, keep that in mind.

Secondly, if you can't produce `g00`, good for you. There's a chance it might happen in the future. You're on version 58, so try 59 if you want to reproduce it. Those empty placeholders are probably added by detection or leftovers from third-party adnetworks, they're the least of your problems comparitively.
