### ISSUE TITLE
IL back again

### ISSUE THREAD

**Issue by peterxiyong** [gorhill/uBO-Extra#63] opened 2017-08-20 15:23 UTC
IL persist at these sites

calgaryherald.com
calgarysun.com
citypaper.com
edmontonjournal.com
edmontonsun.com
edmunds.com
hearthhead.com
leaderpost.com
mamaslatinas.com
montrealgazette.com
nationalpost.com
ottawacitizen.com
ottawasun.com
realclearpolitics.com
theprovince.com
thestarphoenix.com
windsorstar.com
winnipegsun.com

**Comment by gorhill** [comment] 2017-08-20 16:21
Could you please provide exact repro steps on how you came to determine that for the mentioned sites, 3rd-party requests are still disguised as 1st-party requests?

**Comment by peterxiyong** [comment] 2017-08-20 17:34
using chrome Version 60.0.3112.101 (Official Build) (32-bit)
ublock origin 1.13.8
ubo extra 2.45

i see when going to above listed sites, g00 referrer is added to end url and redirected to g00 urls and i see no ads but increasing cookies......when i want to debug that via console,everything is cleared in site those of g00....it happens to all of above sites....there is increase in load on cpu,ram by chrome

`https://streamable.com/akxna`

**Comment by okiehsch** [comment] 2017-08-20 17:37
1. All sites listed in Instart Logic defuser v2 get IL redirects with uBO-Extra 2.45 on my end.
2. `gofugyourself.com`, `hearthhead.com`, `infinitiev.com`, and `mamaslatinas.com` work fine on my end.
3. `calgarysun.com`, `edmontonsun.com`, `ottawasun.com`, `realclearpolitics.com`and `winnipegsun.com`
have sometimes [this](https://github.com/uBlockOrigin/uAssets/issues/546#issuecomment-316249864) issue on my end and get IL redirects, though the only one I can reproduce right now is `realclearpolitics.com`.
4. I accidentally removed `citypaper.com` https://github.com/gorhill/uBO-Extra/commit/e2da8d631a2ff53c9f829609fc07e37d4b33e9e5

**Comment by okiehsch** [comment] 2017-08-20 18:27
@peterxiyong if you add
````
*/abd/instart.js$script,domain=calgarysun.com|edmontonsun.com|ottawasun.com|realclearpolitics.com|winnipegsun.com
````
do you still get redirected on the mentioned sites?

**Comment by peterxiyong** [comment] 2017-08-20 18:27
@okiehsch 
for `hearthhead.com`, on homepage no redirection/g00 thing seen but when clicked individual stories, redirections happen.....only `gofugyyourself.com` and `infinitiev.com` -cannot reproduce now , other sites redirect me , so edited main post accordingly

**Comment by gorhill** [comment] 2017-08-20 18:28
Ok here is what I did given how well the new defuser works:

- Moved ILv4 as ILv1 before other defuser.
- Added all ILv2 sitesto ILv1 sites.
- Added `window.location.reload()` to ILv2's `ReloadWithNoHtmlStreaming()`
- Used filter `/abd.html_streaming/instart.js$script,important` to test

So far all seems to work fine -- this needs more testing once I commit.

**Comment by okiehsch** [comment] 2017-08-20 18:49
> All sites listed in Instart Logic defuser v2 get IL redirects with uBO-Extra 2.45 on my end.

fixed with 2.46 on my end.

> calgarysun.com, edmontonsun.com, ottawasun.com, realclearpolitics.com and winnipegsun.com
have this issue sometimes and get IL redirects, though the only one I can reproduce right now is realclearpolitics.com.

still getting redirects with 2.46
````
*/abd/instart.js$script,domain=calgarysun.com|edmontonsun.com|ottawasun.com|realclearpolitics.com|winnipegsun.com
````
works on my end and could be added to uBO-filters

**Comment by gorhill** [comment] 2017-08-20 18:55
> ````
> */abd/instart.js$script,domain=calgarysun.com|edmontonsun.com|ottawasun.com|realclearpolitics.com|winnipegsun.com
> ````
> works on my end and could be added to uBO-filters

Yes, I tested with `/abd.html_streaming/instart.js$script,important`. The `important` is needed, I saw on one of the site that the script was allowed because of one exception filter in EasyList.

**Comment by okiehsch** [comment] 2017-08-20 19:01
OK, I will add
````
/abd/instart.js$script,important,domain=calgarysun.com|edmontonsun.com|ottawasun.com|realclearpolitics.com|winnipegsun.com
````

**Comment by okiehsch** [comment] 2017-08-20 19:10
Sorry I missed your last edit, I will change it to
````
/abd*/instart.js$script,important,domain=calgarysun.com|edmontonsun.com|ottawasun.com|realclearpolitics.com|winnipegsun.com
````

**Comment by peterxiyong** [comment] 2017-08-20 19:28
hey i was testing with ver 2.46...sometimes this happens.....this happens intermittently 
e.g go to montrealgazette.com
- g00 not reproduced on homepage- go to homepage-click on `business` on top and then invidual story- g00 redirection

i also see if link is opened in new tab by browser behaviour(hyperlink), g00 sticks to it......
Is IL has machine learning technology?

**Comment by gorhill** [comment] 2017-08-20 19:56
Did you test with the `important` filter above? It's key.

**Comment by gorhill** [comment] 2017-08-20 21:46
Testing, I saw an instance of `/instart.js` on `leaderpost.com`. I don't what triggers the server to serve pages with this script, it appears at the top of the page, right after the `<head>` tag. So what I see is that most of the time, the IL code is served inside an inline script tag. Sometimes, inside the `/instart.js` file. To be safe, we should block `/instart.js` for all sites in ILv2.

**Comment by peterxiyong** [comment] 2017-08-21 15:02
hi
what this script do actually.....

https://www.sdad.guru/i10c@p1/cenome/endpoint/nanovisor?inp=nationalpost.com

i see this logged in logger for many sites and is continously fired if blocked via dynamic filtering

**Comment by gorhill** [comment] 2017-08-21 15:12
Does this script get loaded with latest uBO-Extra 2.46 (updated a few minutes ago). This is what matter, no point spending precious time investigating what is not going to be loaded anyways with uBO-Extra.

**Comment by peterxiyong** [comment] 2017-08-21 15:28
i am testing this out....updating in few minutes
instart.js is seen on `realclearpolitics.com`
![2017-08-21_20-54-42](https://user-images.githubusercontent.com/25366549/29526484-7bcac8be-86b3-11e7-9a40-2bdabee5caeb.png)

**Comment by gorhill** [comment] 2017-08-21 15:32
It's ok that it loads, what matters is that the javascritp in it is defused.

What really matters here, what needs to be tested: are 3rd-party network requests disguised as 1st-party network requests? If not, than uBO-Extra is doing its intended job.

**Comment by peterxiyong** [comment] 2017-08-21 15:33
yaa...g00 cookies are not loaded.....thank you

**Comment by gorhill** [comment] 2017-08-21 17:58
> `instart.js` are loaded due to easylist generichide exception filters

uBO-Extra will still defuse IL's code in that file.

**Closed** 2017-08-27 11:02 UTC
