### ISSUE TITLE
Wowhead and IGN ads present again

### ISSUE THREAD

**Issue by HybridEidolon** [gorhill/uBO-Extra#95] opened 2018-07-05 05:32 UTC
Seems like Instart found a way around uBO-Extra? All ads on Wowhead and IGN are loading as of 2018-07-05, and a cursory glance at the dev console reveals that tracking cookies and such are being served through the IGN domains as expected of their tech.

**Comment by gorhill** [comment] 2018-07-05 11:02
I am not being served IL code from the front pages. Please always provide specific URLs when reporting issues, this removes the guess work and saves time.

**Comment by HybridEidolon** [comment] 2018-07-05 15:18
Here's the page I viewed: http://www.wowhead.com/npc=4127/hecklefang-hyena

Browser version was Chrome 68 Stable macOS. uBO and uBO-Extra added, of course, but also Decentraleyes and PrivacyBadger.

**Comment by gorhill** [comment] 2018-07-05 15:24
For some reasons I am not served the IL code, even using a US VPN -- this has happened before. Unless I can find a way to be served the IL javascript, I can't investigate.

**Comment by terrorist96** [comment] 2018-09-02 18:50
I can't reproduce. No ads on my end either.

**Comment by okiehsch** [comment] 2018-09-02 21:00
This should be fixed by https://github.com/gorhill/uBO-Extra/commit/791c696e43eafeb31958f42e74de3e821738ab5b

**Closed by okiehsch** 2018-09-02 21:00 UTC
